[repository]
name = "hyprexpo"
authors = ["GodKeawa"]

commit_pins = [
    ["af923e30d1d24f1f4a4f5cb8308065173c1d9539", "ca2dd0c3a8ceb470612c22ce95746abe660d22a5"],  # 0.55.0
]

[hyprexpo]
description = "hyprexpo — niri scroll expo plugin for Hyprland"
authors = ["GodKeawa"]
output = "hyprexpo.so"
build = [
    "make all"
]

since_hyprland = 6066